---
# Sto hosts, vaftizoume tin omada ypologiston stous opoious theloume
# na ginei i egatastasi, "service"
# Sto remote_user, dilonoume oti o xristis tou apomakrysmenou mixanimatos 
# legetai docker
# Sto vars, dilonoume tin metavliti user gia na ti xrisimopoiisoume parakato
- hosts: service
  remote_user: docker
  gather_facts: no
  vars:
    user: "docker" 
  tasks:

     # ------------------------------------------------------------------------
     # task gia tin enimerosi ton idi egatestimenon paketon meso tou module apt
     # ------------------------------------------------------------------------
    - name: apt update packages
      become: true
      apt:
        update_cache: 'yes'
        force_apt_get: 'yes'
        upgrade: 'dist'
        cache_valid_time: 3600
        install_recommends: true
        autoremove: true

     # ------------------------------------------------------------------
     # task gia tin egatastasi ton akolouthon paketon meso tou module apt
     # ------------------------------------------------------------------
    - name: apt install packages
      become: true
      apt:
        update_cache: 'yes'
        force_apt_get: 'yes'
        install_recommends: true
        autoremove: true
        name: "{{ packages }}"
      vars:
        packages:
         - build-essential
         - git
         - flex
         - bison
         - traceroute
         - curl
         - lynx
         - ruby
         - ruby-dev

     # --------------------------------------------------------------------------------
     # task gia ti dimiourgia katalogou meso tou module file 
     # gia to fluentd apomakrismena me dikaiomata root
     # pou na anikei ston xristi kai sto group docker kai na exei pliri dikaiomata
     # --------------------------------------------------------------------------------
    - name: make /var/log-in
      become: true
      file:
        path: "/var/log-in"
        state: directory
        owner: docker
        group: docker
        mode: '0777'

     # ---------------------------------------------------------------------
     # gem begin
     # task gia ti dimiourgia katalogou gia to gem mesa ston katalogo docker
     # me sigekrimena dikaiomata
     # ---------------------------------------------------------------------
    - name: make dir for gem
      become: true
      file:
        path: "/home/docker/.gem"
        state: directory
        owner: docker
        group: docker
        mode: '0755'

     # ------------------------------------------------------------------------------------------
     # task gia tin egatastasi tou fluentd ekdosis 1.12.0, meso gem
     # ------------------------------------------------------------------------------------------
    - name: gem install  fluentd
      #become: true
      gem:
        name: fluentd
        version: 1.12.0
        state: present
      #environment:
        #CONFIGURE_OPTS: '--disable-install-doc'
        #PATH: '/home/docker/.gem/ruby/2.5.0/bin:{{ ansible_env.PATH }}'

     # ---------------------------------------------------------------
     # task gia tin egatastasi fluentd plugin gia ti MongoDB, meso gem
     # ---------------------------------------------------------------
    - name: gem install fluent-plugin-mongo
      #become: true
      gem:
        name: fluent-plugin-mongo
        state: present

    - name: gem install oj
      #become: true
      gem:
        name: oj
        state: present

    - name: gem install json
      #become: true
      gem:
        name: json
        state: present

    - name: gem install async-http
      #become: true
      gem:
        name: async-http
        version: 0.54.0
        state: present

    - name: gem install ext-monitor
      #become: true
      gem:
        name: ext_monitor
        version: 0.1.2
        state: present

     # ------------------------
     # gem end
     # -------------------------

     # --------------------------------------------------------------------------------------------------
     # task gia ti dimiourgia directory gia to config arxeio tou fluentd apomakrismena me dikaiomata root
     # pou na anikei ston xristi kai sto group docker kai na exei sygekrimena dikaiomata
     # --------------------------------------------------------------------------------------------------
    - name: make dir fluentd
      become: true
      file:
        path: "/fluentd/etc"
        state: directory
        owner: docker
        group: docker
        mode: '0755'

     # --------------------------------------------------------------------------------------------------
     # task gia ti dimiourgia directory gia ta plugins tou fluentd apomakrismena me dikaiomata root
     # pou na anikei ston xristi kai sto group docker kai na exei sygekrimena dikaiomata
     # --------------------------------------------------------------------------------------------------
    - name: make dir fluentd
      become: true
      file:
        path: "/fluentd/plugins"
        state: directory
        owner: docker
        group: docker
        mode: '0755'

     # ------------------------------------------------------------------------------------------------------------------
     # task pou me to module copy antigrafei to fluentd.conf arxeio pou exoume dimiourgisei kai periexei to configuration 
     # tou fluentd, sto directory pou dimiourgisame parapano me xristi kai group to docker kai sygekrimena dikaiomata
     # ------------------------------------------------------------------------------------------------------------------
    - name: cp fluentd.conf
      become: true
      copy:
        src: "./conf/fluent.conf"
        dest: /fluentd/etc/fluent.conf
        owner: docker
        group: docker
        mode: 0755

     # --------------------------------------------------------------------------------------------------
     # task gia tin ekinisi tou fluentd sto paraskinio
     # opou tou leme na diavasei to config arxeio fluent.conf pou antigrapsame ston katalogo /fluentd/etc
     # --------------------------------------------------------------------------------------------------
    - name: start fluentd background
      shell: nohup /home/docker/.gem/ruby/2.5.0/bin/fluentd -c /fluentd/etc/fluent.conf -vv </dev/null >/dev/null 2>&1 &
 
