---
- hosts: service
  remote_user: docker
  gather_facts: no
  vars:
    user: "docker"
  tasks:

     # ------------------------
     # client directory remove
     # -------------------------
    - name: client directory remove
      become: true
      file:
        state: absent
        path: /client_file

     # ------------------------
     # client directory
     # -------------------------
    - name: make /client_file
      become: true
      file:
        path: "/client_file"
        state: directory
        owner: docker
        group: docker
        mode: '0777'

     # ------------------------
     # cp client.js
     # -------------------------
    - name: cp client.js
      become: true
      copy:
        src: "./../app/client.js"
        dest: /client_file/client.js
        owner: docker
        group: docker
        mode: '0777'

     # ------------------------
     # nodesource get
     # -------------------------
    - name: nodesource get
      get_url:
        url: https://deb.nodesource.com/setup_15.x
        dest: /client_file/nodesource_setup.sh

     # ------------------------
     # nodesource run
     # -------------------------
    - name: start nodesource run
      become: true
      command: bash /client_file/nodesource_setup.sh

     # ------------------------
     # nodesource remove
     # -------------------------
    - name: start nodesource remove
      become: true
      file: 
        state: absent
        path: /client_file/nodesource_setup.sh

     # ------------------------
     # apt update
     # -------------------------
    - name: apt update packages
      become: true
      apt:
        update_cache: 'yes'
        force_apt_get: 'yes'
        upgrade: 'dist'
        cache_valid_time: 3600
        install_recommends: true
        autoremove: true

     # ------------------------
     # apt install packages
     # -------------------------
    - name: apt install packages
      become: true
      apt:
        update_cache: 'yes'
        force_apt_get: 'yes'
        install_recommends: true
        autoremove: true
        name: "{{ packages }}"
      vars:
        packages:
         - nodejs

     # ------------------------
     # npm begin
     # -------------------------
    - name: make dir for npm
      become: true
      file:
        path: "/home/docker/.npm"
        state: directory
        owner: docker
        group: docker
        mode: '0755'

    - name: npm install socket.io-client
      npm:
        name: socket.io-client
        version: 4.1.2
        state: present
        path: /client_file/

     # ------------------------
     # npm end
     # -------------------------

