---
- hosts: service
  remote_user: docker
  gather_facts: no
  vars:
    user: "docker"
  tasks:

     # ----------------------------------------------------------------------------------------------
     # task pou diagrafei to directory client_file ean yparxei idi stous workers meso tou module file
     # ----------------------------------------------------------------------------------------------
    - name: client directory remove
      become: true
      file:
        state: absent
        path: /client_file

     # -------------------------------------------------------------------------------
     # task pou dimiourgei to directory client_file stous workers meso tou module file
     # -------------------------------------------------------------------------------
    - name: make /client_file
      become: true
      file:
        path: "/client_file/"
        state: directory
        owner: docker
        group: docker
        mode: '0777'

     # ------------------------------------------------------------------------------------------------------------------
     # task pou antigrafei to arxeio client.js pou periexei ton kodika gia ton client, stous workers meso tou module copy
     # ------------------------------------------------------------------------------------------------------------------
    - name: cp client.js
      become: true
      copy:
        src: "./../app/client.js"
        dest: /client_file/client.js
        owner: docker
        group: docker
        mode: '0755'

     # --------------------------------------------------------------------------------------
     # task pou katevazei to nodesource_setup.sh arxeio stous workers meso tou module get_url
     # --------------------------------------------------------------------------------------
    - name: nodesource get
      get_url:
        url: https://deb.nodesource.com/setup_16.x
        dest: /client_file/nodesource_setup.sh

     # ------------------------------------------------------------------------------------
     # task pou ektelei to nodesource_setup.sh arxeio stous workers meso tou module command
     # ------------------------------------------------------------------------------------
    - name: start nodesource run
      become: true
      command: bash /client_file/nodesource_setup.sh

     # -----------------------------------------------------------------------------------------
     # task pou diagrafei to nodesource_setup.sh arxeio meta tin egatastasi meso tou module file
     # -----------------------------------------------------------------------------------------
    - name: start nodesource remove
      become: true
      file: 
        state: absent
        path: /client_file/nodesource_setup.sh

     # --------------------------------------------------------------------------------------
     # task gia tin enimerosi ton idi egatestimenon paketon stous workers meso tou module apt
     # --------------------------------------------------------------------------------------
    - name: apt update packages
      become: true
      apt:
        update_cache: 'yes'
        force_apt_get: 'yes'
        upgrade: 'dist'
        cache_valid_time: 3600
        install_recommends: true
        autoremove: true

     # --------------------------------------------------------------------
     # task gia tin egatastasi tou nodejs stous workers meso tou module apt
     # --------------------------------------------------------------------
    - name: apt install packages
      become: true
      apt:
        update_cache: 'yes'
        force_apt_get: 'yes'
        install_recommends: true
        autoremove: true
        name: "{{ packages }}"
      vars:
        packages:
         - nodejs

     # ---------------------------------------------------------------------
     # gem begin
     # task gia ti dimiourgia katalogou gia to npm mesa ston katalogo docker
     # me sigekrimena dikaiomata
     # ---------------------------------------------------------------------
    - name: make dir for npm
      become: true
      file:
        path: "/home/docker/.npm"
        state: directory
        owner: docker
        group: docker
        mode: '0755'

     # --------------------------------------------------------------------
     # task gia tin egatastasi tou socket.io-client ekdosis 4.1.2, meso npm
     # --------------------------------------------------------------------
    - name: npm install socket.io-client
      become: true
      npm:
        name: socket.io-client
        version: 4.1.2
        state: present
        path: /client_file

     # ------------------------
     # npm end
     # -------------------------

